config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :games do
    resources :locations
    resources :weapons
    resources :suspects
  end
  root 'welcome#index'
  
  get 'games/index'
  root 'games#index'
  
  get 'games/new'
  root 'games#new'
  
  get 'welcome/suspects'
  root 'welcome#suspects'
  
  get 'welcome/weapons'
  root 'welcome#weapons'
  
  get 'welcome/locations'
  root 'welcome#locations'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
    has_many :locations, dependent: :destroy
    has_many :suspects, dependent: :destroy
    has_many :weapons, dependent: :destroy
    validates :name, presence: true, length: { minimum: 5}
    validates :date, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :game
end

app/models/suspect.rb
class Suspect < ApplicationRecord
  belongs_to :game
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    def index
        @games = Game.all
    end
    def new
        @game = Game.new
    end
    def create
        @game = Game.new(game_params)
        if @game.save
            redirect_to @game
        else
            render 'new'
        end
    end
    def show
        @game = Game.find(params[:id])
    end
    def edit
        @game = Game.find(params[:id])
    end
    def update
        @game = Game.find(params[:id])
        if @game.update(game_params)
            redirect_to @game
        else
            render 'edit'
        end
    end
    def destroy
        @game = Game.find(params[:id])
        @game.destroy
        redirect_to games_path
    end
end

private
    def game_params
        params.require(:game).permit(:name, :date)
    end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def create
        @game = Game.find(params[:game_id])
        @location = @game.locations.create(location_params)
        redirect_to game_path(@game)
    end
    
    def destroy
       @game = Game.find(params[:game_id])
       @location = @game.locations.find(params[:id])
       @location.destroy
       redirect_to game_path(@game)
    end
    private
        def location_params
            params.require(:location).permit(:locName)
        end
end

app/controllers/suspects_controller.rb
class SuspectsController < ApplicationController
    def create
        @game = Game.find(params[:game_id])
        @suspect = @game.suspects.create(suspect_params)
        redirect_to game_path(@game)
    end
    
    def destroy
       @game = Game.find(params[:game_id])
       @suspect = @game.suspects.find(params[:id])
       @suspect.destroy
       redirect_to game_path(@game)
    end
    private
        def suspect_params
            params.require(:suspect).permit(:susName)
        end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
    def create
        @game = Game.find(params[:game_id])
        @weapon = @game.weapons.create(weapon_params)
        redirect_to game_path(@game)
    end
    
    def destroy
       @game = Game.find(params[:game_id])
       @weapon = @game.weapons.find(params[:id])
       @weapon.destroy
       redirect_to game_path(@game)
    end
    private
        def weapon_params
            params.require(:weapon).permit(:wepName)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/suspects_helper.rb
module SuspectsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for :game, url: games_path do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@game.errors.count, "error") %> prohibited
        this game from being saved:
      </h2>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/games/edit.html.erb
<div class="bg-section center-text container">
    <h1>Edit Game Information</h1>
    <%= render 'form' %>
</div>

app/views/games/index.html.erb
<div class="bg-section center-text container">
  <h1>Games</h1>
 
<div class="row"> 
  <table class="container ">
    <tr>
      <th>Game Name</th>
      <th>Date</th>
    </tr>
 
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.date %></td>
        <td><%= link_to 'Show', game_path(game) %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy',
                                  game_path(game),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
</div>
</div>

app/views/games/new.html.erb
<div class="bg-section center-text container">
    <h1>New Game</h1>
    <%= render 'form' %>
</div>

app/views/games/show.html.erb
<div class="bg-section  container">
<p>
    <strong>Game Name:</strong>
    <%= @game.name %>
    
</p>
<p>
    <strong>Game Date:</strong>
    <%= @game.date %>
</p>
<div class="row">
    <div>
        <h2>Suspects</h2>
        <%= render @game.suspects %>

        <h2>Add a Suspect:</h2>
        <%=  render 'suspects/form' %>
    </div>
    <div>
        <h2>Weapons</h2>
        <%= render @game.weapons %>

        <h2>Add a Weapon:</h2>
        <%=  render 'weapons/form' %>
    </div>

    <div>
        <h2>Locations</h2>
        <%= render @game.locations %>

        <h2>Add a Location:</h2>
        <%=  render 'locations/form' %>
    </div>
</div>

<%= link_to 'Game Saves List', games_path %>
</div>

app/views/layouts/_navbar.html.erb
<div class="header center-text">
    <h1>CLUE Card Tracker</h1>
</div>
<nav>
    <%= link_to "Home", "/welcome/index", :class => "menuOption" %>
    <%= link_to "My Trackers", "/games", :class => "menuOption" %>
    <%= link_to "New Tracker", "/games/new", :class => "menuOption"%>
    <%= link_to "Suspects", "/welcome/suspects", :class => "menuOption"%>
    <%= link_to "Locations", "/welcome/locations", :class => "menuOption"%>
    <%= link_to "Weapons", "/welcome/weapons", :class => "menuOption"%>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClueTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_for([@game, @game.locations.build]) do |f| %>
  <p>
    <%= f.label :locName, "Location:" %><br>
    <%= f.select :locName, [['Library','Library'],['Study','Study'],['Hall','Hall'], ['Lounge','Lounge'], 
      ['Dining Room','Dining Room'], ['Kitchen','Kitchen'], ['Ballroom','Ballroom'], ['Conservatory','Conservatory'],
      ['Billard Room','Billiard Room']] %>
  </p>
  
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/locations/_location.html.erb
<%= link_to '--', [location.game, location],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
<%= location.locName %>
<br>

app/views/suspects/_form.html.erb
<%= form_for([@game, @game.suspects.build]) do |f| %>
  <p>
    <%= f.label :susName, "Suspect:" %><br>
    <%= f.select :susName, [['Mrs. Peacock','Mrs. Peacock'],['Miss Scarlett','Miss Scarlett'],
      ['Rev. Green','Rev. Green'], ['Colonel Mustard','Colonel Mustard'],
      ['Professor Plum','Professor Plum'], ['Mrs. White','Mrs. White']] %>
  </p>
  
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/suspects/_suspect.html.erb
<%= link_to '--', [suspect.game, suspect],
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
<%= suspect.susName %>

<br>

app/views/weapons/_form.html.erb
<%= form_for([@game, @game.weapons.build]) do |f| %>
  <p>
    <%= f.label :wepName, "Weapon:" %><br>
    <%= f.select :wepName, [['Gun','Gun'],['Pipe','Pipe'],['Knife','Knife'], 
    ['Candlestick','Candlestick'], ['Rope','Rope'], ['Wrench','Wrench']] %>
  </p>
  
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/weapons/_weapon.html.erb
<%= link_to '--', [weapon.game, weapon],
                method: :delete,
                data: { confirm: 'Are you sure?' }%>
<%= weapon.wepName %>
<br>

app/views/welcome/index.html.erb
<div class="bg-section center-text container">
    <h2><strong>Welcome to the Clue Card Tracker!</strong></h2>
    <img src="https://media3.giphy.com/media/gSYzK9VGVQxoY/giphy.gif" alt="cluegif">
    <h3>Here, you can track all the cards you know aren't in the "confidential packet," 
    <br> and you can easily figure out which cards ARE in the packet so you can win the game!</h3>
    <h5>NOTE: This application does not include the board game, Clue.</h5>
</div>

app/views/welcome/locations.html.erb
<div class="flex row card-cont">
    <img src="https://i.imgur.com/0hCDcm3.png" alt="ballroom" class="card container">
    <img src="https://i.imgur.com/jEj0peL.png" alt="billiard" class="card container">
    <img src="https://i.imgur.com/NINwfHE.png" alt="conservatory" class="card container">
    <img src="https://i.imgur.com/Rk6Mt9U.png" alt="dining" class="card container">
    <img src="https://i.imgur.com/1aE9z8M.png" alt="hall" class="card container">
    <img src="https://i.imgur.com/MVsnTjH.png" alt="library" class="card container">
    <img src="https://i.imgur.com/dnGjugE.png" alt="lounge" class="card container">
    <img src="https://i.imgur.com/S7p91SO.png" alt="study" class="card container">
    <img src="https://i.imgur.com/ZygtQ1v.png" alt="kitchen" class="card container">
</div>

app/views/welcome/suspects.html.erb
<div class="flex row card-cont">
    <img src="https://i.pinimg.com/736x/9d/17/68/9d17687582b552b3a11c76d068b310ed.jpg" alt="Mustard" class="card container">
    <img src="https://i.pinimg.com/736x/95/5e/3f/955e3f53cad1de2fd769ffdde8d2c8c1.jpg" alt="Plum" class="card container">
    <img src="https://i.pinimg.com/originals/b9/60/93/b960938ccb284a04e416dacda76a09ac.jpg" alt="Peacock" class="card container">
    <img src="https://i.pinimg.com/736x/b3/62/ff/b362ff17a90b60791a7ed2ac8a5288d9.jpg" alt="Green" class="card container">
    <img src="https://i.pinimg.com/736x/8d/29/7b/8d297bdd2c4409c8cd398942b3313b1b.jpg" alt="Scarlett" class="card container">
    <img src="https://i.pinimg.com/736x/63/cc/b9/63ccb920d1858136a3cc91cbd88991dd.jpg" alt="White" class="card container">
</div>

app/views/welcome/weapons.html.erb
<div class="flex row card-cont">
    <img src="https://imgur.com/GokEOn1.png" alt="wrench" class="card container">
    <img src="https://imgur.com/TJ7SIo8.png" alt="rope" class="card container">
    <img src="https://imgur.com/qlIOJKm.png" alt="pipe" class="card container">
    <img src="https://imgur.com/by2yDu5.png" alt="candle" class="card container">
    <img src="https://i.imgur.com/294ZcNS.png" alt="dagger" class="card container">
    <img src="https://i.imgur.com/Ubrgr6T.png" alt="revolver" class="card container">
</div>